export interface Session {
  token: string;
  playerId: string;
}

/**
 * Maps session tokens to player ids so a reconnecting client (same token) rebinds to its
 * existing seat/hand instead of being treated as a new join. Tokens are generated by the caller
 * (via `expo-crypto`'s synchronous `randomUUID()` on device, or `crypto.randomUUID()` in tests/
 * Node) and handed to `register`.
 */
export class SessionManager {
  private tokenToPlayerId = new Map<string, string>();
  private playerIdToToken = new Map<string, string>();

  register(token: string, playerId: string): void {
    this.tokenToPlayerId.set(token, playerId);
    this.playerIdToToken.set(playerId, token);
  }

  resolve(token: string): string | undefined {
    return this.tokenToPlayerId.get(token);
  }

  tokenFor(playerId: string): string | undefined {
    return this.playerIdToToken.get(playerId);
  }

  remove(playerId: string): void {
    const token = this.playerIdToToken.get(playerId);
    if (token) this.tokenToPlayerId.delete(token);
    this.playerIdToToken.delete(playerId);
  }
}
